apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-backup
  namespace: <namespace>
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-home-data
        - name: backup-dir
          emptyDir: {}
        - name: oci-key
          secret:
            secretName: oci-key
      containers:
      - name: vaultwarden-backup
        image: raackley/vaultwarden-backup:latest
        env:
          - name: OCI_USER_ID
            value: <your OCI value here>
          - name: OCI_KEY_FILE_PATH
            value: <from oci-key secret>
          - name: OCI_KEY_FILE_FINGERPRINT
            value: <your OCI value here>
          - name: OCI_TENANCY
            value: <your OCI value here>
          - name: OCI_REGION
            value: <your OCI value here>
          - name: OCI_COMPARTMENT_ID
            value: <your OCI value here>
          - name: OCI_BUCKET_NAME
            value: <your OCI value here>
        volumeMounts:
          - name: data
            mountPath: /data
          - name: backup-dir
            mountPath: /backups
          - name: oci-key
            readOnly: true
            mountPath: "/oci"
      restartPolicy: Never
  backoffLimit: 4
